apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-kv-store
spec:
  provider:
    azurekv:
      authType: ServicePrincipal
      vaultUrl: https://homelab-staging-kv01.vault.azure.net/
      tenantId: 7d75783a-4e24-43cf-9eb2-7369fa8b11de
      authSecretRef:
        clientId:
          name: az-creds
          key: ClientID
          namespace: external-secrets
        clientSecret:
          name: az-creds
          key: ClientSecret
          namespace: external-secrets