apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pvc-cloner
  namespace: audiobookshelf
spec:
  serviceName: pvc-cloner
  replicas: 1
  selector:
    matchLabels:
      app: pvc-cloner
  template:
    metadata:
      labels:
        app: pvc-cloner
    spec:
      containers:
        - name: cloner
          image: alpine
          command:
            - /bin/sh
            - -c
            - |
              apk add --no-cache rsync
              echo "Copying books..."
              rsync -av /old-audiobooks/ /new-audiobooks/
              echo "Copying config..."
              rsync -av /old-config/ /new-config/
              echo "Copying metadata..."
              rsync -av /old-meta/ /new-meta/
              echo "Copy complete"
              sleep 3600
          volumeMounts:
            - name: old-audiobooks
              mountPath: /old-audiobooks
            - name: new-audiobooks
              mountPath: /new-audiobooks
            - name: old-config
              mountPath: /old-config
            - name: new-config
              mountPath: /new-config
            - name: old-meta
              mountPath: /old-meta
            - name: new-meta
              mountPath: /new-meta
          securityContext:
            allowPrivilegeEscalation: false

      volumes:
        - name: old-audiobooks
          persistentVolumeClaim:
            claimName: audiobookshelf-audiobooks
        - name: new-audiobooks
          persistentVolumeClaim:
            claimName: audiobookshelf-audiobooks-syn
        - name: old-config
          persistentVolumeClaim:
            claimName: audiobookshelf-config
        - name: new-config
          persistentVolumeClaim:
            claimName: audiobookshelf-config-syn
        - name: old-meta
          persistentVolumeClaim:
            claimName: audiobookshelf-metadata
        - name: new-meta
          persistentVolumeClaim:
            claimName: audiobookshelf-metadata-syn
