apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: it-tools
  template:
    metadata:
      labels:
        app: it-tools
    spec:
      containers:
        - name: it-tools
          image: ghcr.io/corentinth/it-tools:2024.10.22-7ca5933
          ports:
            - containerPort: 8080
              # protocol: TCP
          # securityContext:
          #   allowPrivilegeEscalation: false
      restartPolicy: Always
