apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:nFLN+FYkb4EbmMWARsLCiRrrifG70x9UDcRNpr0jx3zEoC/KyFxa+mieKii86liZQBNSsD25n2S0MAEt8Hu0fldPFdBZKP79vyQHEjyfpTjBw0iwYgUCl4XZqEXe7GXS9cAXb5uLz78y4DfFm7hORK97epE3UqwZbpfG5SFHPdlqX6vRHMw/BtuW4KokLTbABIUHgoZPSDX2MpXu4+5PZ2/w2n1FSL/d7KPii3zf3iH4jNW2AmKvk249wqR7VmIz+2oMwzR0mISVk+N7hFnNNe/C1oTOAbWvbBcJktkyxp9GhQuXefZkbHjHqxg=,iv:fmfcSaRY/1IhsrXJxpZG3VkqfQ4vDT2h+GTtO+nOkF0=,tag:U/te4IUtLk7DNUYZq4EahA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: abs-tunnel-credentials
sops:
    age:
        - recipient: age12nz8jcvxqslhm0jqk8lssf7gnukjls92up5vz87axf8fnas8xdfqng887y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUk9MRzBLQkE4d0JEY2pC
            OHZHc093K0lqQjhSQ0tsMFlGb2hrNFNhMFU4ClJLbVl2R083NUZ1ejZCMFZGR016
            OWJHR1JidS9ud2QreUVyQ2Z4bEJlR0EKLS0tIE9FVUZGQTJjRFZUam80QVlrNndV
            S0RoYklIWHdpUUhDMzBKS2U3STZaQ00K012JM8dKEeoxlyU+mWPLOmBCNqXez2+a
            QmYNxgm8CRD5qILEf+C66wB7ooBBPAtuQZZVhuKTZSDk/DkrpQDJJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-22T14:48:05Z"
    mac: ENC[AES256_GCM,data:vG1XGKuIQeZmVgtXyOosVpAE/QuWikCLyLsp52XvgUiXryc7tHQr5l/Xl0smemRaX/xK6TG91DVD3tX+TVkS40JygUiH7vHydvMZJcAN04ZhInBRKlXxEATzgDJyVZSsgec4I10v/IKWISK82B997kxvXFZ/JDDwilenrdNje3g=,iv:DoUCx+D6fyoJZ8ZT9m8NI06K1RnaQvraKMJ2x1/plvk=,tag:LUbbW0FrCDgRL97keTuxRQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
