apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:P4ChXzTgEmgfHqYPJnv6/Hro4gZficwP2x66FKL38WHt69qbRw+djHRStXIike4dxhTW2q/0mbarK+9K2Vhjk/hbbaO/yJVkmuAOCg4kiEOyVrmSBmboHvswfAS6zEPa4Bbod2adLZK1fwxzRjwRzCW2yDZaZ0ijt+lArnNbli3Rj3sRcFZgp0wTzxyF7V/cnPdeFOcm+3oIaNewJDyunrYnJRoXgbnw99De70o+4mMIi97ltrAJYIILjhxf0LyV0FNSSIltJdzkm+jnPHdnGE4hDRj7vMM8HOFF7u5PNzlDTuLiqNg0WdbOXe4=,iv:n+7qjBWdJ7/RWie8wB6tPBbDsjmChTDz11+Gnave4Ao=,tag:J4y+ai2RRfVjxEV3GhrcBQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age12nz8jcvxqslhm0jqk8lssf7gnukjls92up5vz87axf8fnas8xdfqng887y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3QkR5UXN0OUFaanY1c0d0
            Wi81dkpqdFYvdkZjb2l0Q1R4alBsUGNkK3pzCld3TWwvK0lHOSs5SWtQR3BMM0I1
            Y3IwQUFXMmdSUVpoODNocXMrcTNzSXMKLS0tIFJYbEw5bitZT3drODZ6U1FqTDNT
            NmtGNDVGT2NOTXoxdHRNU3dqT3g5MHcKv3pP3/ddcZUQgivDJ68X0wXiXrmgpiD3
            nTSsMRZk3lSQ8MFvAWEutFctyNAn7kmp1+O+pFjNF0t446Finrqt8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-14T22:59:11Z"
    mac: ENC[AES256_GCM,data:xmtaGdvkgIC6FhAQiDgv4ls0tEkSagfB3+vgbM5aM7NB1j+TiV1sWUM8Nhcqsk78pKluQLSzndLerbSVIKTp4lgJcwEKnvAMgsN/omZOzeZTsCI4JBCWSRhIk/Y5A2dQWfHq0hCWc5BtiY8WI/S5QF6q0DHkArq6GOvU3h5q5DQ=,iv:Gi8MHagey89dPLC/k/BNM4E8QjLcFVFeyoxw1+7gIRQ=,tag:nxJ1tvLVi35mRkZQw646+Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
