apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n
spec:
  ingressClassName: traefik
  rules:
  - host: "n8n.kubeklepsch.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: n8n
            port:
              number: 5678
