apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n
spec:
  ingressClassName: traefik
  rules:
    - host: "eneighten.kubeklepsch.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: n8n
                port:
                  number: 5678
