apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synology-csi-secrey
  namespace: kube-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: client-info.yml
      remoteRef:
        key: SynCSI-client-info
