apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:PhWCa9Na3ws=,iv:eKWWYZ1DI3Yvc52eJwgJNJEBtkT9ZlnzEutq5A7mE7k=,tag:0w+cT26ZCwDcOxb+kxi1pQ==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:34RT6Vwl033k79x+KUtlhOQLLq+fdN371xZFRgB96Jg=,iv:QSd3zI6DFahRTauYHPwtFv987J0i/hfuIEwnfz7hajY=,tag:N1kAEXxucy94x/6Gvtj3Zw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: linkding-container-env-secret
sops:
    age:
        - recipient: age12nz8jcvxqslhm0jqk8lssf7gnukjls92up5vz87axf8fnas8xdfqng887y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWHhobmZaQjdrZkpDczhI
            VlQ1elU1cEkvRkNyd0s2L3ZYZnhpbStIaGxVCitkV0ROQTFtcnZQNzNtNklxMkhH
            clpkQ0lhVHU3WEVjeW1SaXFqQVYxc2cKLS0tIEg1ZldVNXZkNmNwTk4yaWlWYW00
            bFVxdjhtTmFhU2VJQmV3eDZ0RGZ4RU0KKlnSAUVTIRpU9tI/IDT9Y0f4nzW1g9Sq
            1ayAZx6EA+wxzcaLhOaA6Xa8mjmAokYtxhVhiT75EPPBIZwiNiCPsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-15T15:56:33Z"
    mac: ENC[AES256_GCM,data:7R57FPXl/b+rp4O0v0eFJnmiC2U+wcc+feFG+yAYv7+INlzwna5vt+jbFflbKOw1/42QWZZIvYNlvt/iIweSzeoOM3pPkLT3Ntg3N29Z43juo8hUIitmgcCuFuZpj2XjEuellrXwe7RWcz6U6ORvFZTkH7YmDYVUqPQw+L/o8bY=,iv:W6WJ4cKonof+IisTAKVtNxBMqUw6IcmSqNob/UIkx6Q=,tag:ZFnvskrkgdIF+liB5Jj5bg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
